name: Semantic Release Version
on:
  push:
    branches:
      - 'main'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@main

      - name: Extract commit messages
        run: |
          MAJOR_MSG=$(git log --grep='+major' --no-merges -1 --pretty=%B | sed 's/+major//g')
          if [ -z "$MAJOR_MSG" ]; then
              MAJOR_MSG="No major changes in this release."
          fi
          echo "MAJOR_MSG=$MAJOR_MSG" >> $GITHUB_ENV
      
          MINOR_MSG=$(git log --grep='+minor' --no-merges -1 --pretty=%B | sed 's/+minor//g')
          if [ -z "$MINOR_MSG" ]; then
              MINOR_MSG="No minor changes in this release."
          fi
          echo "MINOR_MSG=$MINOR_MSG" >> $GITHUB_ENV
      
          PATCH_MSG=$(git log --grep='+patch' --no-merges -1 --pretty=%B | sed 's/+patch//g')
          if [ -z "$PATCH_MSG" ]; then
              PATCH_MSG="No patch changes in this release."
          fi
          echo "PATCH_MSG=$PATCH_MSG" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
          release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
          body: |
            ## ğŸš€ Changes in this Release
            -----------------------
            ### ğŸ’¥ Major Changes:
            - ${{ env.MAJOR_MSG }}

            ### âœ¨ Minor Changes:
            - ${{ env.MINOR_MSG }}

            ### ğŸ› Patch Changes:
            - ${{ env.PATCH_MSG }}
          draft: false
          prerelease: false
