name: Semantic Release Version
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@main

      - name: Extract commit messages
        run: |
          MAJOR_MSG=$(git log --grep='+major' --no-merges -1 --pretty=%B | sed 's/+major//g')
          if [ -z "$MAJOR_MSG" ]; then
              MAJOR_MSG="No major changes in this release."
          fi
          echo "MAJOR_MSG=$MAJOR_MSG" >> $GITHUB_ENV
      
          MINOR_MSG=$(git log --grep='+minor' --no-merges -1 --pretty=%B | sed 's/+minor//g')
          if [ -z "$MINOR_MSG" ]; then
              MINOR_MSG="No minor changes in this release."
          fi
          echo "MINOR_MSG=$MINOR_MSG" >> $GITHUB_ENV
      
          OTHER_MSG=$(git log --no-merges -1 --pretty=%B)
          if [ -z "$OTHER_MSG" ]; then
              OTHER_MSG="No other changes in this release."
          fi
          echo "OTHER_MSG=$OTHER_MSG" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
          release_name: Release ${{ steps.gitversion.outputs.majorMinorPatch }}
          body: |
            ## ğŸš€ Changes in this Release
            -----------------------
            ### ğŸ’¥ Major Changes:
            - ${{ env.MAJOR_MSG }}

            ### âœ¨ Minor Changes:
            - ${{ env.MINOR_MSG }}

            ### ğŸ“ Other Changes:
            - ${{ env.OTHER_MSG }}
          draft: false
          prerelease: false
